repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-json
-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black
        exclude: ^.*\b(migrations)\b.*$
-   repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
    -   id: isort
        name: isort (python)
        exclude: ^.*\b(migrations)\b.*$
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.2
    hooks:
    -   id: ruff
        name: ruff (python linter)
        exclude: ^.*\b(migrations)\b.*$
    -   id: ruff-format
        name: ruff format
        exclude: ^.*\b(migrations)\b.*$
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
    -   id: mypy
        exclude: ^.*\b(migrations)\b.*$
