services:
  api:
    build:
      context: .
      dockerfile: ./docker/production/django/Dockerfile
    image: ${API_IMAGE_NAME?A variável API_IMAGE_NAME precisa ser definida}:${API_IMAGE_TAG?A variável API_IMAGE_TAG precisa ser definida}
    command: /start
    volumes:
      - .:/app
      - static_volume:/data/nitapi/staticfiles
      - media_volume:/data/nitapi/mediafiles
    expose:
      - "8000"
    ports:
      - "8000:8000"
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    depends_on:
      - postgres
      - redis
    networks:
      - nitapi
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 1024M
          cpus: "1"
        reservations:
          memory: 512M
          cpus: "0.50"
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first # Iniciar a nova instância antes de derrubar a antiga
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      healthcheck:
        test: curl -f http://localhost:8000/health/ || exit 1
        interval: 30s
        timeout: 10s
        retries: 3
        start_period: 30s

  redis:
    image: redis:6-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - nitapi

  celery_worker:
    build:
      context: .
      dockerfile: ./docker/production/django/Dockerfile
    image: ${API_IMAGE_NAME?A variável API_IMAGE_NAME precisa ser definida}:${API_IMAGE_TAG?A variável API_IMAGE_TAG precisa ser definida}
    user: "1001:1001"
    command: >
      celery -A nitapi worker
      --loglevel=info
      --concurrency=2
      --prefetch-multiplier=1
      --max-tasks-per-child=100
      --heartbeat-interval=60
      --pool=prefork
      --queues=request_queue,batch_processing_queue,process_os_request_queue,process_os_batch_queue,process_callback_queue,process_operation_os_queue,request_operation_queue
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    depends_on:
      - redis
      - api
    restart: always
    networks:
      - nitapi
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 1024M
          cpus: "0.50"
        reservations:
          memory: 256M
          cpus: "0.25"
      update_config:
        parallelism: 1 # Atualizar uma instância por vez
        delay: 10s # Esperar 10 segundos entre cada atualização
        order: start-first # Iniciar a nova instância antes de derrubar a antiga
      restart_policy:
        condition: on-failure # Reiniciar apenas em caso de falha
        delay: 5s
        max_attempts: 3
        window: 120s

  postgres:
    build:
      context: .
      dockerfile: ./docker/local/postgres/Dockerfile
    container_name: postgres
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - ${HOME}/backups/prd:/backups
    env_file:
      - ./.envs/.production/.postgres
    networks:
      - nitapi
    deploy:
      resources:
        limits:
          memory: 2048M
          cpus: "1"
        reservations:
          memory: 512M
          cpus: "0.25"
    restart: always

networks:
  nitapi:
    driver: bridge
    external: true

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}
  static_volume:
  media_volume:
