# Generated by Django 5.0.1 on 2025-09-02 21:47

import tinymce.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Atualizado em"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        null=True, verbose_name="Deletado em"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        editable=False,
                        verbose_name="Está ativo?",
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Rua",
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Bairro",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Número",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Cidade",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AC", "Acre"),
                            ("AL", "Alagoas"),
                            ("AP", "Amapá"),
                            ("AM", "Amazonas"),
                            ("BA", "Bahia"),
                            ("CE", "Ceará"),
                            ("DF", "Distrito Federal"),
                            ("ES", "Espírito Santo"),
                            ("GO", "Goiás"),
                            ("MA", "Maranhão"),
                            ("MT", "Mato Grosso"),
                            ("MS", "Mato Grosso do Sul"),
                            ("MG", "Minas Gerais"),
                            ("PA", "Pará"),
                            ("PB", "Paraíba"),
                            ("PR", "Paraná"),
                            ("PE", "Pernambuco"),
                            ("PI", "Piauí"),
                            ("RJ", "Rio de Janeiro"),
                            ("RN", "Rio Grande do Norte"),
                            ("RS", "Rio Grande do Sul"),
                            ("RO", "Rondônia"),
                            ("RR", "Roraima"),
                            ("SC", "Santa Catarina"),
                            ("SP", "São Paulo"),
                            ("SE", "Sergipe"),
                            ("TO", "Tocantins"),
                        ],
                        max_length=255,
                        null=True,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="País",
                    ),
                ),
                (
                    "complement",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Complemento",
                    ),
                ),
                (
                    "cep",
                    models.CharField(
                        blank=True, max_length=9, null=True, verbose_name="CEP"
                    ),
                ),
            ],
            options={
                "verbose_name": "Endereço",
                "verbose_name_plural": "Endereços",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Atualizado em"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        null=True, verbose_name="Deletado em"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        editable=False,
                        verbose_name="Está ativo?",
                    ),
                ),
                (
                    "user_welcome_subject",
                    models.CharField(
                        default="Bem-vindo - Backoffice Brasil",
                        max_length=255,
                        verbose_name="Novo usuário (subject)",
                    ),
                ),
                (
                    "user_welcome",
                    tinymce.models.HTMLField(
                        blank=True,
                        help_text="Variáveis: {{ link }}, {{ email }}",
                        null=True,
                        verbose_name="Novo usuário",
                    ),
                ),
                (
                    "user_reset_password_subject",
                    models.CharField(
                        default="Atualizar senha - Backoffice Brasil",
                        max_length=255,
                        verbose_name="Atualizar senha (subject)",
                    ),
                ),
                (
                    "user_reset_password",
                    tinymce.models.HTMLField(
                        blank=True,
                        help_text="Variáveis: {{ link }}, {{ email }},",
                        null=True,
                        verbose_name="Atualizar senha",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email",
                "verbose_name_plural": "Emails",
                "ordering": ("-created_at",),
                "abstract": False,
                "select_on_save": True,
            },
        ),
    ]
