# Generated by Django 5.0.1 on 2025-09-03 18:55

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commons", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="email",
            options={
                "ordering": ("-created_at",),
                "select_on_save": True,
                "verbose_name": "Configuração de E-mail",
                "verbose_name_plural": "Configurações de E-mail",
            },
        ),
        migrations.RemoveField(
            model_name="email",
            name="user_reset_password",
        ),
        migrations.RemoveField(
            model_name="email",
            name="user_reset_password_subject",
        ),
        migrations.RemoveField(
            model_name="email",
            name="user_welcome",
        ),
        migrations.RemoveField(
            model_name="email",
            name="user_welcome_subject",
        ),
        migrations.AddField(
            model_name="email",
            name="notification_subject",
            field=models.CharField(
                default="Nova notificação",
                help_text="Assunto padrão para notificações gerais",
                max_length=255,
                verbose_name="Notificação (assunto)",
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="notification_template",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Template HTML para notificações gerais. Variáveis: {{ nome }}, {{ email }}, {{ mensagem }}, {{ site_name }}",
                null=True,
                verbose_name="Notificação (template)",
            ),
        ),
    ]
